# Generated by Django 3.2.8 on 2022-05-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_auto_20190113_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='energyusage',
            name='cdate',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='energyusage',
            name='ctime',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
